let chapters = [];
let chapterData = {};
let currentChapterId = "law";
let currentIndex = 0;
let activeTab = "intro";
const markerState = loadState("integratedMarkerState", {});
const visibleAnswers = loadState("integratedVisibleAnswers", {});
const $ = (id) => document.getElementById(id);
const menuButton = $("menuButton"), menuOverlay = $("menuOverlay"), sideMenu = $("sideMenu"), menuCloseButton = $("menuCloseButton"), chapterItemNav = $("chapterItemNav"), chapterLabel = $("chapterLabel"), chapterTitle = $("chapterTitle"), itemNo = $("itemNo"), itemTitle = $("itemTitle"), counter = $("counter"), content = $("content"), prevBtn = $("prevBtn"), nextBtn = $("nextBtn"), redMarkerToggle = $("redMarkerToggle"), blueMarkerToggle = $("blueMarkerToggle"), boostBold = $("boostBold");
function loadState(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } }
function saveState(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch { /* localStorageが使えない場合も操作は継続する */ } }
function currentChapter() { return chapters.find((chapter) => chapter.id === currentChapterId); }
function currentItems() { return chapterData[currentChapterId] || []; }
function contentHtml(value) { return value || '<p class="empty">内容がありません。</p>'; }
function openMenu() { menuOverlay.hidden = false; sideMenu.classList.add("open"); document.body.classList.add("menu-open"); sideMenu.setAttribute("aria-hidden", "false"); menuButton.setAttribute("aria-expanded", "true"); }
function closeMenu() { menuOverlay.hidden = true; sideMenu.classList.remove("open"); document.body.classList.remove("menu-open"); sideMenu.setAttribute("aria-hidden", "true"); menuButton.setAttribute("aria-expanded", "false"); }
function renderSideMenu() { chapterItemNav.innerHTML = chapters.map((chapter) => { const items = chapterData[chapter.id] || []; return `<section class="nav-chapter"><h3>第${chapter.chapter}章 ${chapter.title}</h3><div class="nav-items">${items.map((item, index) => `<button type="button" class="nav-item ${chapter.id === currentChapterId && index === currentIndex ? "active" : ""}" data-chapter-id="${chapter.id}" data-index="${index}"><span class="nav-item-no">${String(item.itemNo).padStart(2,"0")}</span><span>${item.title}</span></button>`).join("")}</div></section>`; }).join(""); }
function markers() { return [...content.querySelectorAll(".marker[data-marker-id]")]; }
function isMarkerOn(id) { return markerState[id] !== false; }
function setMarkerState(marker, on) { marker.classList.toggle("marker-on", on); marker.classList.toggle("marker-off", !on); marker.setAttribute("aria-pressed", String(on)); marker.setAttribute("title", on ? "クリックでマーカーOFF" : "クリックでマーカーON"); }
function updateMarkerButtons() { for (const [button, selector, label] of [[redMarkerToggle,".marker-red","赤"],[blueMarkerToggle,".marker-blue","青"]]) { const matches = markers().filter((marker) => marker.matches(selector)); const allOn = matches.length > 0 && matches.every((marker) => marker.classList.contains("marker-on")); button.disabled = matches.length === 0; button.textContent = allOn ? `${label}を隠す` : `${label}を表示`; button.setAttribute("aria-pressed", String(allOn)); } }
function applyMarkers() { markers().forEach((marker) => { marker.setAttribute("role", "button"); marker.setAttribute("tabindex", "0"); setMarkerState(marker, isMarkerOn(marker.dataset.markerId)); }); updateMarkerButtons(); }
function setColorMarkers(colorClass) { const matches = markers().filter((marker) => marker.classList.contains(colorClass)); const allOn = matches.length > 0 && matches.every((marker) => marker.classList.contains("marker-on")); matches.forEach((marker) => { markerState[marker.dataset.markerId] = !allOn; setMarkerState(marker, !allOn); }); saveState("integratedMarkerState", markerState); updateMarkerButtons(); }
function renderContent(item) { if (activeTab === "intro") { content.innerHTML = contentHtml(item.intro) + (item.introImage ? `<img class="intro-image" src="${item.introImage}" alt="${item.introImageAlt || ""}" />` : ""); } else if (activeTab === "body") { content.innerHTML = contentHtml(item.body); } else if (!item.questions.length) { content.innerHTML = '<p class="empty">この項目には参考問題がありません。</p>'; } else { content.innerHTML = item.questions.map((question) => `<section class="question question-card" data-question-id="${question.id}"><h3>問題 ${question.questionNo}</h3><div class="question-text">${contentHtml(question.question)}</div><ol class="choices">${question.choices.map((choice) => `<li>${choice}</li>`).join("")}</ol><button class="answer-toggle" type="button" aria-expanded="${Boolean(visibleAnswers[question.id])}">${visibleAnswers[question.id] ? "回答を隠す" : "回答表示"}</button><div class="answer answer-block" ${visibleAnswers[question.id] ? "" : "hidden"}><p><strong>正解：${question.answer}</strong></p>${contentHtml(question.explanation)}</div></section>`).join(""); } applyMarkers(); }
function render() { const chapter = currentChapter(), items = currentItems(), item = items[currentIndex]; if (!chapter || !item) { content.innerHTML = '<p class="empty">データを読み込めませんでした。</p>'; return; } renderSideMenu(); chapterLabel.textContent = `第${chapter.chapter}章`; chapterTitle.textContent = chapter.title; itemNo.textContent = `項目 ${String(item.itemNo).padStart(2,"0")}`; itemTitle.textContent = item.title; counter.textContent = `${currentIndex + 1} / ${items.length}・問題 ${item.questions.length}`; prevBtn.disabled = currentIndex === 0; nextBtn.disabled = currentIndex === items.length - 1; renderContent(item); document.body.classList.toggle("boost-bold", boostBold.checked); document.querySelectorAll(".tabs button").forEach((button) => button.classList.toggle("active", button.dataset.tab === activeTab)); }
function selectChapter(id, index = 0) { currentChapterId = id; currentIndex = Math.max(0, Math.min(index, currentItems().length - 1)); activeTab = "intro"; render(); }
function toggleMarker(marker) { const next = !isMarkerOn(marker.dataset.markerId); markerState[marker.dataset.markerId] = next; setMarkerState(marker, next); saveState("integratedMarkerState", markerState); updateMarkerButtons(); }
menuButton.addEventListener("click", openMenu); menuCloseButton.addEventListener("click", closeMenu); menuOverlay.addEventListener("click", closeMenu); chapterItemNav.addEventListener("click", (event) => { const button = event.target.closest("button[data-chapter-id]"); if (button) { selectChapter(button.dataset.chapterId, Number(button.dataset.index)); closeMenu(); } }); document.querySelector(".tabs").addEventListener("click", (event) => { const button = event.target.closest("button[data-tab]"); if (button) { activeTab = button.dataset.tab; render(); } }); prevBtn.addEventListener("click", () => { currentIndex = Math.max(0, currentIndex - 1); activeTab = "intro"; render(); }); nextBtn.addEventListener("click", () => { currentIndex = Math.min(currentItems().length - 1, currentIndex + 1); activeTab = "intro"; render(); }); boostBold.addEventListener("change", render); redMarkerToggle.addEventListener("click", () => setColorMarkers("marker-red")); blueMarkerToggle.addEventListener("click", () => setColorMarkers("marker-blue")); document.addEventListener("keydown", (event) => { if (event.key === "Escape") closeMenu(); }); content.addEventListener("click", (event) => { const marker = event.target.closest(".marker[data-marker-id]"); if (marker) { toggleMarker(marker); return; } const answerButton = event.target.closest(".answer-toggle"); if (!answerButton) return; const card = answerButton.closest(".question-card"), id = card.dataset.questionId, answer = card.querySelector(".answer-block"); visibleAnswers[id] = !visibleAnswers[id]; answer.hidden = !visibleAnswers[id]; answerButton.textContent = visibleAnswers[id] ? "回答を隠す" : "回答表示"; answerButton.setAttribute("aria-expanded", String(Boolean(visibleAnswers[id]))); saveState("integratedVisibleAnswers", visibleAnswers); }); content.addEventListener("keydown", (event) => { if ((event.key === "Enter" || event.key === " ") && event.target.closest(".marker[data-marker-id]")) { event.preventDefault(); toggleMarker(event.target.closest(".marker[data-marker-id]")); } });
let touchStart = null; content.addEventListener("pointerdown", (event) => { if (event.target.closest("button,input,.marker")) { touchStart = null; return; } touchStart = { x:event.clientX, y:event.clientY, edge: event.clientY < 72 ? "top" : event.clientY > window.innerHeight - 72 ? "bottom" : "" }; }); content.addEventListener("pointerup", (event) => { if (!touchStart) return; const dx = event.clientX - touchStart.x, dy = event.clientY - touchStart.y; if (Math.abs(dx) > 70 && Math.abs(dx) > Math.abs(dy)) { if (dx < 0 && activeTab !== "questions") activeTab = activeTab === "intro" ? "body" : "questions"; if (dx > 0 && activeTab !== "intro") activeTab = activeTab === "questions" ? "body" : "intro"; render(); } else if (Math.abs(dy) > 70 && Math.abs(dy) > Math.abs(dx)) { if (touchStart.edge === "top" && dy > 0 && currentIndex > 0) { currentIndex--; activeTab = "intro"; render(); } if (touchStart.edge === "bottom" && dy < 0 && currentIndex < currentItems().length - 1) { currentIndex++; activeTab = "intro"; render(); } } touchStart = null; });
async function loadData() { if (Array.isArray(window.INTEGRATED_CHAPTERS) && window.INTEGRATED_CHAPTER_DATA) { chapters = window.INTEGRATED_CHAPTERS; chapterData = window.INTEGRATED_CHAPTER_DATA; currentChapterId = chapters[0]?.id || "law"; render(); return; } const response = await fetch("data/chapters.json"); if (!response.ok) throw new Error(`chapters.json HTTP ${response.status}`); chapters = await response.json(); const entries = await Promise.all(chapters.map(async (chapter) => { const file = await fetch(`data/${chapter.dataFile}`); if (!file.ok) throw new Error(`${chapter.dataFile} HTTP ${file.status}`); return [chapter.id, await file.json()]; })); chapterData = Object.fromEntries(entries); currentChapterId = chapters[0]?.id || "law"; render(); }
loadData().catch((error) => { content.innerHTML = `<p class="empty">データを読み込めませんでした。</p><p class="empty">${error.message}</p>`; });
